
#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update


spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
            
            
  datasource:
    generate-unique-name: false
    

   
server:
  error:
    path: "/error"
    