
spring:
  datasource:
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update



  
    properties:
      persistence:
        validation:
          mode:none  
            
            
#  datasource:
#    generate-unique-name: false
    